spring.application.name=MVCProj02
<<<<<<< HEAD

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
=======
>>>>>>> branch 'main' of https://github.com/Jumersha01/Spring-SpringBoot-Lab
